const THRESHOLD_SECONDS = 60; // in case you are changing this, change the cron time too.

const LOCK_TTL_IN_SECONDS = 10;

const SCHEDULE_JOB_MAX_RETRIES = 3;

const SCHEDULE_JOB_BASE_DELAY_MS = 500;

const SCHEDULE_JOB_MAX_JITTER_MS = 150;

const EXTERNAL_SERVICE_TIMEOUT_IN_SECONDS = 10;

export {
  THRESHOLD_SECONDS,
  LOCK_TTL_IN_SECONDS,
  SCHEDULE_JOB_MAX_RETRIES,
  SCHEDULE_JOB_BASE_DELAY_MS,
  SCHEDULE_JOB_MAX_JITTER_MS,
  EXTERNAL_SERVICE_TIMEOUT_IN_SECONDS,
};
